### ISSUE TITLE
checkStatus fails when there is no queryResult

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/alerts#226]
NotificationService.checkStatus can fail when `qr = QueryResult.findById(qr.id)` returns null. 

A subset of the exception is
```
java.lang.NullPointerException: Cannot get property 'lastChecked' on null object
        at au.org.ala.alerts.NotificationService.$tt__checkStatus(NotificationService.groovy:108)
        at au.org.ala.alerts.NotificationService$__tt__checkQueryForFrequency_closure65.doCall(NotificationService.groovy:881)
        at au.org.ala.alerts.NotificationService.$tt__checkQueryForFrequency(NotificationService.groovy:877)
        at au.org.ala.alerts.NotificationService.$tt__checkQueryForFrequency(NotificationService.groovy:856)
```

**Comment by qifeng-bai** [comment]
Fixed, linked to #228
