### ISSUE TITLE
error getting new images

### ISSUE THREAD

**Issue by matthewandrews** [AtlasOfLivingAustralia/alerts#29]
This is appearing in alerts.log in production each hour:

```
2017-03-07 07:48:01,170 [NotificationService]  [QUERY 5] There was a problem checking the URL: http://biocache.ala.org.au/ws/occurrences/search?q=first_loaded_date%3A[2017-03-07T06%3A48%3A01Z%20TO%20*]&fq=data_resource_uid%3Adr364&sort=first_loaded_date&dir=desc&pageSize=60&facets=basis_of_record&fq=multimedia%3AImage
org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [au.org.ala.alerts.PropertyPath#10]
	at au.org.ala.alerts.NotificationService$_hasChanged_closure2.doCall(NotificationService.groovy:178)
	at au.org.ala.alerts.NotificationService.hasChanged(NotificationService.groovy:177)
	at au.org.ala.alerts.NotificationService.checkStatus(NotificationService.groovy:60)
	at au.org.ala.alerts.NotificationService$_checkQueryForFrequency_closure8.doCall(NotificationService.groovy:418)
	at au.org.ala.alerts.NotificationService.checkQueryForFrequency(NotificationService.groovy:416)
	at au.org.ala.alerts.NotificationService.checkQueryForFrequency(NotificationService.groovy:399)
	at ala.postie.HourlyQueriesJob.execute(HourlyQueriesJob.groovy:13)
	at grails.plugins.quartz.GrailsJobFactory$GrailsJob.execute(GrailsJobFactory.java:104)
	at grails.plugins.quartz.QuartzDisplayJob.execute(QuartzDisplayJob.groovy:27)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

**Comment by nickdos** [comment]
Biocache search is OK - returns 3322 results, so issue is alerts DB or code related.

**Comment by Rita-C** [comment]
`PropertyPath#10` belongs to https://alerts.ala.org.au/query/show/5
```
mysql> mysql> select * from property_path where id<20;
+----+---------+------------------+--------------------+-----------------------+-----------------------+----------+
| id | version | fire_when_change | fire_when_not_zero | json_path             | name                  | query_id |
+----+---------+------------------+--------------------+-----------------------+-----------------------+----------+
|  1 |       0 |                  |                   | totalRecords          | totalRecords          |        1 |
|  2 |       0 |                  |                    | occurrences[0].rowKey | last_assertion_record |        1 |
|  3 |       0 |                  |                   | totalRecords          | totalRecords          |        2 |
|  4 |       0 |                  |                    | occurrences[0].rowKey | last_loaded_record    |        2 |
|  5 |       0 |                  |                   | totalRecords          | totalRecords          |        3 |
|  6 |       0 |                  |                    | occurrences[0].rowKey | last_loaded_record    |        3 |
|  7 |       0 |                  |                   | totalRecords          | totalRecords          |        4 |
|  8 |       0 |                  |                    | occurrences[0].rowKey | last_loaded_record    |        4 |
|  9 |       0 |                  |                   | totalRecords          | totalRecords          |        5 |
| 11 |       0 |                  |                    | layerList             | layer_count           |        6 |
| 12 |       0 |                  |                    | $                     | dataset_count         |        7 |
| 13 |       0 |                  |                   | totalRecords          | totalRecords          |        8 |
| 14 |       0 |                  |                    | occurrences[0].rowKey | last_loaded_record    |        8 |
| 15 |       0 |                  |                   | totalRecords          | totalRecords          |        9 |
| 16 |       0 |                  |                    | occurrences[0].rowKey | last_loaded_record    |        9 |
| 17 |       0 |                  |                   | totalRecords          | totalRecords          |       10 |
| 18 |       0 |                  |                    | occurrences[0].rowKey | last_loaded_record    |       10 |
| 19 |       0 |                  |                   | totalRecords          | totalRecords          |       11 |
+----+---------+------------------+--------------------+-----------------------+-----------------------+----------+
18 rows in set (0.00 sec)

```

An alternative solution is to add the missing row:
```
insert into alerts.property_path (id, version, json_path, query_id, name, fire_when_not_zero, fire_when_change)
values (10, 0, 'occurrences[0].rowKey', 5, 'last_assertion_record', '', '')
```

**Comment by Rita-C** [comment]
Checked prod db, seemed deletion was done:
```
mysql> select * from property_value where property_path_id = 10;
Empty set (0.00 sec)
```

There was no error in log anymore.
@nickdos , can we close this issue?

**Comment by nickdos** [comment]
closing
